### ISSUE TITLE
Error while updating property 'source' of a view managed by: RNCWebView

### ISSUE THREAD

**Issue by olcayertas** [vinzscam/react-native-file-viewer#72]
When I try to open a png file on my Huawei P20 Lite I am getting this error:
```
RNCWebView
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:773)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:846)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
	... 17 more
Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for uri cannot be cast from ReadableNativeMap to String
	at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:139)
	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:127)
	at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:161)
	at com.reactnativecommunity.webview.RNCWebViewManager.setSource(RNCWebViewManager.java:431)
	... 19 more
```
Android 9
Version: 2.0.1
React Native: 0.61.5

**Comment by olcayertas** [comment]
I have found the problem and it is not related to this library.

**Comment by dilas12345** [comment]
> I have found the problem and it is not related to this library.

How did you solve it, please? I am facing similar issue
