### ISSUE TITLE
Application crashes while trying to open xlsx file

### ISSUE THREAD

**Issue by olcayertas** [vinzscam/react-native-file-viewer#73]
**UnexpectedNativeTypeException**
I am trying to open a xlxs file on emulator with Android 10. If I install any application wich can open xlsx it works fine but when no application installed it crashes with following native exception:

```
com.facebook.react.bridge.UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String
	at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:139)
	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:127)
	at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:161)
	at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:195)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:214)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:919)
```
Version: 2.0.1
React Native: 0.61.5

**Comment by vinzscam** [comment]
Sorry but I can't reproduce the issue.
Could you please send me your snippet if you haven't been able to fix it?
